franccoina/Macedonia

- index.html
Cambio realizado para eliminar una etiqueta br
> fix:delete <br>

- src/scss/styles.scss
Cambio de paddding bottom para el footer en scss
> fix:change of padding-bot for footer, scss

- src/scss/styles.scss
Se cambia de nuevo este aspecto del footer para aumentarlo un poco
> fix:second change of padding-bot for footer, scss

- index.html
Cambio de la url del anchor para whatsapp
> fix:change of wa.me url for whatsapp anchor

- src/pages/booking.html
- src/scss/booking.scss
Añade section revisar reservas del administrador
> feat:adding files for booking  section  from admin

- src/pages/edit.html
- src/scss/edit.scss
Añade section para editar del administrador
> feat:adding files for edit  section from admin

- index.html
- src/pages/explora.html
- src/scss/explora.scss
- src/scss/styles.scss
Se desarrolla toda la parte de esqueleto del explora, para mas adelante poder comenzar con sus funcionalidades de research
> feat:developing the explora section, galleries and searching bar

- src/scss/explora.scss
Cambio de archivo scss para borrar linea de codigo duplicada
> fix:removing duplicated lines of code

- src/pages/edit.html
- src/scss/edit.scss
Agregando subtítulos a section editar
> feat:adding captions

- index.html
- src/js/admi.js
- src/js/explora.js
- src/pages/admi.html
- src/pages/explora.html
- src/scss/admi.scss
- src/scss/styles.scss
Se añade el esqueleto y parte del diseño del login para el administra
> feat:adding and designing the login section for the administra

- src/js/admi.js
Se cambia el codigo escrito en el js del admi
> fix:change of admi.js

- src/pages/admi.html
- src/scss/admi.scss
- src/scss/explora.scss
Se cambian los inputs de las secciones explora y administra
> fix:change of input settings and design

- src/scss/admi.scss
- src/scss/explora.scss
Se arregla problema con el degradado del login
> fix:setting gradient fade for login

- index.html
- public/data/database.json
- src/js/admi.js
- src/js/create.js
- src/pages/admi.html
- src/pages/booking.html
- src/pages/create.html
- src/pages/edit.html
- src/pages/explora.html
- src/scss/admi.scss
- src/scss/booking.scss
- src/scss/create.scss
- src/scss/edit.scss
- src/scss/explora.scss
- src/scss/styles.scss
Se termina de configurar el login, con sus funciones integradas en js. Se arreglan visuales de secciones del administra, para registrar, editar y ver reservas, y tambien se organizan las visuales para movil de toda la pagina
> fix:finishing functions and design for login, administra sections and explora. Also visuals for mobile

- src/js/booking.js
- src/js/edit.js
- src/pages/booking.html
- src/pages/create.html
- src/pages/edit.html
- src/scss/admi.scss
- src/scss/booking.scss
- src/scss/create.scss
- src/scss/edit.scss
Se arreglan problemas en la section administer
> fix:solving problems with administer sections

- src/js/booking.js
- src/js/edit.js
- src/pages/booking.html
- src/pages/create.html
- src/pages/edit.html
- src/scss/admi.scss
- src/scss/booking.scss
- src/scss/create.scss
- src/scss/edit.scss
Arreglando problemas en la section administer
Anteriomente se envio desdes la cuenta de Santycadavid10 por un error de enlazar la cuenta con el pc en riwi
> fix:intruder id issue

- src/js/explora.js
- src/pages/explora.html
- src/scss/explora.scss
trabajando en la section explora
> feat:working on explora section

- src/pages/explora.html
- src/scss/explora.scss
> feat:adding modals

- public/data/database.json
- src/js/explora.js
- src/pages/explora.html
- src/scss/admi.scss
Se ultiman detalles en nuestro proyecto Macedonia
> fix:finishig our loved project

- README.md
> feat:Adding readme files and closure of the project Macedonia

- README.md
- index.html
- src/controllers/admi.js
- src/controllers/booking.js
- src/controllers/create.js
- src/controllers/edit.js
- src/views/admi.html
- src/views/booking.html
- src/views/contacta.html
- src/views/create.html
- src/views/edit.html
- src/views/explora.html
- vercel.json
Se añade archivo vercel.json con rutas de las diferentes vistas del proyecto, para asi poder navegar en el proyecto al desplegar en Vercel.
> feat:Adding vercel.json file for deployment

- package-lock.json
- package.json
- src/controllers/booking.js
- src/controllers/create.js
- src/controllers/edit.js
- vercel.json
- vite.config.js
Se añade lógica necesaria para la creación de versión de distribución de Vite.
> feat:Adding build dist logic

- index.html
- vercel.json
- vite.config.js
Correciones para probar despliegue en Vercel.
> fix:Correcting some files for deployment
